### ISSUE TITLE
Use local module on Example

### ISSUE THREAD

**Issue by benevbright** [benevbright/react-navigation-collapsible#3]
I want to use the local module on Example, like using `npm install ./..`

But the packger gave me error

```
error: bundling failed: Error: Unable to resolve module `react` from `/Users/bright/Dev/react-navigation-collapsible/index.js`: Module `react` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/bright/Dev/react-navigation-collapsible/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:167:1306)
    at ResolutionRequest.resolveDependency (/Users/bright/Dev/react-navigation-collapsible/example/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:80:16)
    at DependencyGraph.resolveDependency (/Users/bright/Dev/react-navigation-collapsible/example/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
    at Object.resolve (/Users/bright/Dev/react-navigation-collapsible/example/node_modules/metro/src/lib/transformHelpers.js:116:25)
    at dependencies.map.result (/Users/bright/Dev/react-navigation-collapsible/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/bright/Dev/react-navigation-collapsible/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
    at /Users/bright/Dev/react-navigation-collapsible/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (/Users/bright/Dev/react-navigation-collapsible/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)
```

**Comment by benevbright** [comment]
Ok, https://github.com/facebook/react-native/issues/637

It's because npm makes the symlink. 
If I use yarn, it works fine. 

But I'll just keep `package.json` with github link. Because I don't want some people to fail to run example when they're using npm and don't know what's going on.
